export const seed = async (knex) => {
  await knex("community_chests").del();

  await knex("community_chests").insert([
    {
      id: 1,
      instruction: "Advance to Go (Collect $200)",
      type: "credit_and_move",
      amount: 200,
      position: 0,
      extra: null,
    },
    {
      id: 2,
      instruction: "Bank error in your favor – Collect $200",
      type: "credit",
      amount: 200,
      position: null,
      extra: null,
    },
    {
      id: 3,
      instruction: "Doctor’s fees – Pay $50",
      type: "debit",
      amount: 50,
      position: null,
      extra: null,
    },
    {
      id: 4,
      instruction: "From sale of stock you get $50",
      type: "credit",
      amount: 50,
      position: null,
      extra: null,
    },
    {
      id: 5,
      instruction:
        "Get Out of Jail Free – This card may be kept until needed, or traded/sold",
      type: "community_chest",
      amount: null,
      position: null,
      extra: JSON.stringify({ rule: "get_out_of_jail_free" }),
    },
    {
      id: 6,
      instruction:
        "Go to Jail – Go directly to jail – Do not pass Go – Do not collect $200",
      type: "debit_and_move",
      amount: 0,
      position: null,
      extra: JSON.stringify({ rule: "go_to_jail" }),
    },
    {
      id: 7,
      instruction: "Grand Opera Night – Collect $50 from every player",
      type: "credit",
      amount: 50,
      position: null,
      extra: JSON.stringify({ per_player: true }),
    },
    {
      id: 8,
      instruction: "Holiday Fund matures – Receive $100",
      type: "credit",
      amount: 100,
      position: null,
      extra: null,
    },
    {
      id: 9,
      instruction: "Income tax refund – Collect $20",
      type: "credit",
      amount: 20,
      position: null,
      extra: null,
    },
    {
      id: 10,
      instruction: "It is your birthday – Collect $10 from every player",
      type: "credit",
      amount: 10,
      position: null,
      extra: JSON.stringify({ per_player: true }),
    },
    {
      id: 11,
      instruction: "Life insurance matures – Collect $100",
      type: "credit",
      amount: 100,
      position: null,
      extra: null,
    },
    {
      id: 12,
      instruction: "Hospital Fees – Pay $100",
      type: "debit",
      amount: 100,
      position: null,
      extra: null,
    },
    {
      id: 13,
      instruction: "School Fees – Pay $50",
      type: "debit",
      amount: 50,
      position: null,
      extra: null,
    },
    {
      id: 14,
      instruction: "Receive $25 consultancy fee",
      type: "credit",
      amount: 25,
      position: null,
      extra: null,
    },
    {
      id: 15,
      instruction:
        "You are assessed for street repairs – $40 per house – $115 per hotel",
      type: "debit",
      amount: null,
      position: null,
      extra: JSON.stringify({ per_house: 40, per_hotel: 115 }),
    },
    {
      id: 16,
      instruction:
        "You have won second prize in a beauty contest – Collect $10",
      type: "credit",
      amount: 10,
      position: null,
      extra: null,
    },
    {
      id: 17,
      instruction: "You inherit $100",
      type: "credit",
      amount: 100,
      position: null,
      extra: null,
    },
  ]);
};
