export const seed = async (knex) => {
  await knex("properties").del();

  await knex("properties").insert([
    {
      id: 0,
      type: "corner",
      name: "Go",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#D3D3D3",
      position: "bottom",
      grid_row: 11,
      grid_col: 11,
      icon: "/game/go.svg",
    },
    {
      id: 1,
      type: "property",
      name: "Axone Avenue",
      price: 60,
      rent_site_only: 2,
      rent_one_house: 10,
      rent_two_houses: 30,
      rent_three_houses: 90,
      rent_four_houses: 160,
      rent_hotel: 250,
      cost_of_house: 50,
      is_mortgaged: false,
      group_id: 1,
      color: "#8B4513",
      position: "bottom",
      grid_row: 11,
      grid_col: 10,
      icon: "/game/tokyo.svg",
    },
    {
      id: 2,
      type: "community_chest",
      name: "Community Chest",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#F0E68C",
      position: "bottom",
      grid_row: 11,
      grid_col: 9,
      icon: "/game/seoul.svg",
    },
    {
      id: 3,
      type: "property",
      name: "Onlydust Avenue",
      price: 60,
      rent_site_only: 4,
      rent_one_house: 20,
      rent_two_houses: 60,
      rent_three_houses: 180,
      rent_four_houses: 320,
      rent_hotel: 450,
      cost_of_house: 50,
      is_mortgaged: false,
      group_id: 1,
      color: "#8B4513",
      position: "bottom",
      grid_row: 11,
      grid_col: 8,
      icon: "/game/shanghai.svg",
    },
    {
      id: 4,
      type: "luxury_tax",
      name: "Luxury Tax",
      price: 100,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#DC143C",
      position: "bottom",
      grid_row: 11,
      grid_col: 7,
      icon: "/game/taipei.svg",
    },
    {
      id: 5,
      type: "property",
      name: "IPFS Railroad",
      price: 200,
      rent_site_only: 25,
      rent_one_house: 50,
      rent_two_houses: 100,
      rent_three_houses: 200,
      rent_four_houses: 400,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#000000",
      position: "bottom",
      grid_row: 11,
      grid_col: 6,
      icon: "/game/sydney.svg",
    },
    {
      id: 6,
      type: "property",
      name: "Aave Avenue",
      price: 100,
      rent_site_only: 6,
      rent_one_house: 30,
      rent_two_houses: 90,
      rent_three_houses: 270,
      rent_four_houses: 400,
      rent_hotel: 550,
      cost_of_house: 50,
      is_mortgaged: false,
      group_id: 2,
      color: "#ADD8E6",
      position: "bottom",
      grid_row: 11,
      grid_col: 5,
      icon: "/game/dubai.svg",
    },
    {
      id: 7,
      type: "chance",
      name: "Chance",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#FFD700",
      position: "bottom",
      grid_row: 11,
      grid_col: 4,
      icon: "/game/newyork.svg",
    },
    {
      id: 8,
      type: "property",
      name: "Starkware Street",
      price: 100,
      rent_site_only: 6,
      rent_one_house: 30,
      rent_two_houses: 90,
      rent_three_houses: 270,
      rent_four_houses: 400,
      rent_hotel: 550,
      cost_of_house: 50,
      is_mortgaged: false,
      group_id: 2,
      color: "#ADD8E6",
      position: "bottom",
      grid_row: 11,
      grid_col: 3,
      icon: "/game/london.svg",
    },
    {
      id: 9,
      type: "property",
      name: "Ethereum Expressway",
      price: 120,
      rent_site_only: 8,
      rent_one_house: 40,
      rent_two_houses: 100,
      rent_three_houses: 300,
      rent_four_houses: 450,
      rent_hotel: 600,
      cost_of_house: 50,
      is_mortgaged: false,
      group_id: 2,
      color: "#ADD8E6",
      position: "bottom",
      grid_row: 11,
      grid_col: 2,
      icon: "/game/paris.svg",
    },
    {
      id: 10,
      type: "corner",
      name: "Jail",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#A9A9A9",
      position: "left",
      grid_row: 11,
      grid_col: 1,
      icon: "/game/jail.svg",
    },
    {
      id: 11,
      type: "property",
      name: "Solana Street",
      price: 140,
      rent_site_only: 10,
      rent_one_house: 50,
      rent_two_houses: 150,
      rent_three_houses: 450,
      rent_four_houses: 625,
      rent_hotel: 750,
      cost_of_house: 100,
      is_mortgaged: false,
      group_id: 3,
      color: "#FF69B4",
      position: "left",
      grid_row: 10,
      grid_col: 1,
      icon: "/game/berlin.svg",
    },
    {
      id: 12,
      type: "property",
      name: "Hydrogen Utility",
      price: 150,
      rent_site_only: 4,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#708090",
      position: "left",
      grid_row: 9,
      grid_col: 1,
      icon: "/game/moscow.svg",
    },
    {
      id: 13,
      type: "property",
      name: "Polygon Place",
      price: 140,
      rent_site_only: 10,
      rent_one_house: 50,
      rent_two_houses: 150,
      rent_three_houses: 450,
      rent_four_houses: 625,
      rent_hotel: 750,
      cost_of_house: 100,
      is_mortgaged: false,
      group_id: 3,
      color: "#FF69B4",
      position: "left",
      grid_row: 8,
      grid_col: 1,
      icon: "/game/cape.svg",
    },
    {
      id: 14,
      type: "property",
      name: "Optimism Avenue",
      price: 160,
      rent_site_only: 12,
      rent_one_house: 60,
      rent_two_houses: 180,
      rent_three_houses: 500,
      rent_four_houses: 700,
      rent_hotel: 900,
      cost_of_house: 100,
      is_mortgaged: false,
      group_id: 3,
      color: "#FF69B4",
      position: "left",
      grid_row: 7,
      grid_col: 1,
      icon: "/game/madrid.svg",
    },
    {
      id: 15,
      type: "property",
      name: "Arweave Railroad",
      price: 200,
      rent_site_only: 25,
      rent_one_house: 50,
      rent_two_houses: 100,
      rent_three_houses: 200,
      rent_four_houses: 400,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#000000",
      position: "left",
      grid_row: 6,
      grid_col: 1,
      icon: "/game/rome.svg",
    },
    {
      id: 16,
      type: "property",
      name: "Sui Street",
      price: 180,
      rent_site_only: 14,
      rent_one_house: 70,
      rent_two_houses: 200,
      rent_three_houses: 550,
      rent_four_houses: 750,
      rent_hotel: 950,
      cost_of_house: 100,
      is_mortgaged: false,
      group_id: 4,
      color: "#FFA500",
      position: "left",
      grid_row: 5,
      grid_col: 1,
      icon: "/game/lagos.svg",
    },
    {
      id: 17,
      type: "community_chest",
      name: "Community Chest",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#F0E68C",
      position: "left",
      grid_row: 4,
      grid_col: 1,
      icon: "/game/lagos2.svg",
    },
    {
      id: 18,
      type: "property",
      name: "Celestia Street",
      price: 180,
      rent_site_only: 14,
      rent_one_house: 70,
      rent_two_houses: 200,
      rent_three_houses: 550,
      rent_four_houses: 750,
      rent_hotel: 950,
      cost_of_house: 100,
      is_mortgaged: false,
      group_id: 4,
      color: "#FFA500",
      position: "left",
      grid_row: 3,
      grid_col: 1,
      icon: "/game/nairobi.svg",
    },
    {
      id: 19,
      type: "property",
      name: "Monad Mall",
      price: 200,
      rent_site_only: 16,
      rent_one_house: 80,
      rent_two_houses: 220,
      rent_three_houses: 600,
      rent_four_houses: 800,
      rent_hotel: 1000,
      cost_of_house: 100,
      is_mortgaged: false,
      group_id: 4,
      color: "#FFA500",
      position: "left",
      grid_row: 2,
      grid_col: 1,
      icon: "/game/cairo.svg",
    },
    {
      id: 20,
      type: "corner",
      name: "Free Parking",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#B22222",
      position: "top",
      grid_row: 1,
      grid_col: 1,
      icon: "/game/parking.svg",
    },
    {
      id: 21,
      type: "property",
      name: "Near Protocol",
      price: 220,
      rent_site_only: 18,
      rent_one_house: 90,
      rent_two_houses: 250,
      rent_three_houses: 700,
      rent_four_houses: 875,
      rent_hotel: 1050,
      cost_of_house: 150,
      is_mortgaged: false,
      group_id: 5,
      color: "#FF0000",
      position: "top",
      grid_row: 1,
      grid_col: 2,
      icon: "/game/tokyo2.svg",
    },
    {
      id: 22,
      type: "chance",
      name: "Chance",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#FFD700",
      position: "top",
      grid_row: 1,
      grid_col: 3,
      icon: "/game/dubai2.svg",
    },
    {
      id: 23,
      type: "property",
      name: "Avalanche Avenue",
      price: 220,
      rent_site_only: 18,
      rent_one_house: 90,
      rent_two_houses: 250,
      rent_three_houses: 700,
      rent_four_houses: 875,
      rent_hotel: 1050,
      cost_of_house: 150,
      is_mortgaged: false,
      group_id: 5,
      color: "#FF0000",
      position: "top",
      grid_row: 1,
      grid_col: 4,
      icon: "/game/london2.svg",
    },
    {
      id: 24,
      type: "property",
      name: "Cosmos Court",
      price: 240,
      rent_site_only: 20,
      rent_one_house: 100,
      rent_two_houses: 300,
      rent_three_houses: 750,
      rent_four_houses: 925,
      rent_hotel: 1100,
      cost_of_house: 150,
      is_mortgaged: false,
      group_id: 5,
      color: "#FF0000",
      position: "top",
      grid_row: 1,
      grid_col: 5,
      icon: "/game/paris2.svg",
    },
    {
      id: 25,
      type: "property",
      name: "Polygon Railroad",
      price: 200,
      rent_site_only: 25,
      rent_one_house: 50,
      rent_two_houses: 100,
      rent_three_houses: 200,
      rent_four_houses: 400,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#000000",
      position: "top",
      grid_row: 1,
      grid_col: 6,
      icon: "/game/railroad.svg",
    },
    {
      id: 26,
      type: "property",
      name: "Filecoin Field",
      price: 260,
      rent_site_only: 22,
      rent_one_house: 110,
      rent_two_houses: 330,
      rent_three_houses: 800,
      rent_four_houses: 975,
      rent_hotel: 1150,
      cost_of_house: 150,
      is_mortgaged: false,
      group_id: 6,
      color: "#FFFF00",
      position: "top",
      grid_row: 1,
      grid_col: 7,
      icon: "/game/filecoin.svg",
    },
    {
      id: 27,
      type: "property",
      name: "ICP Street",
      price: 260,
      rent_site_only: 22,
      rent_one_house: 110,
      rent_two_houses: 330,
      rent_three_houses: 800,
      rent_four_houses: 975,
      rent_hotel: 1150,
      cost_of_house: 150,
      is_mortgaged: false,
      group_id: 6,
      color: "#FFFF00",
      position: "top",
      grid_row: 1,
      grid_col: 8,
      icon: "/game/icp.svg",
    },
    {
      id: 28,
      type: "property",
      name: "Nuclear Utility",
      price: 150,
      rent_site_only: 4,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#708090",
      position: "top",
      grid_row: 1,
      grid_col: 9,
      icon: "/game/nuclear.svg",
    },
    {
      id: 29,
      type: "property",
      name: "zkSync Street",
      price: 280,
      rent_site_only: 24,
      rent_one_house: 120,
      rent_two_houses: 360,
      rent_three_houses: 850,
      rent_four_houses: 1025,
      rent_hotel: 1200,
      cost_of_house: 150,
      is_mortgaged: false,
      group_id: 6,
      color: "#FFFF00",
      position: "top",
      grid_row: 1,
      grid_col: 10,
      icon: "/game/zksync.svg",
    },
    {
      id: 30,
      type: "corner",
      name: "Go To Jail",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#FF0000",
      position: "right",
      grid_row: 1,
      grid_col: 11,
      icon: "/game/gotojail.svg",
    },
    {
      id: 31,
      type: "property",
      name: "Scroll Street",
      price: 300,
      rent_site_only: 26,
      rent_one_house: 130,
      rent_two_houses: 390,
      rent_three_houses: 900,
      rent_four_houses: 1100,
      rent_hotel: 1275,
      cost_of_house: 200,
      is_mortgaged: false,
      group_id: 7,
      color: "#008000",
      position: "right",
      grid_row: 2,
      grid_col: 11,
      icon: "/game/scroll.svg",
    },
    {
      id: 32,
      type: "property",
      name: "Linea Lane",
      price: 300,
      rent_site_only: 26,
      rent_one_house: 130,
      rent_two_houses: 390,
      rent_three_houses: 900,
      rent_four_houses: 1100,
      rent_hotel: 1275,
      cost_of_house: 200,
      is_mortgaged: false,
      group_id: 7,
      color: "#008000",
      position: "right",
      grid_row: 3,
      grid_col: 11,
      icon: "/game/linea.svg",
    },
    {
      id: 33,
      type: "community_chest",
      name: "Community Chest",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#F0E68C",
      position: "right",
      grid_row: 4,
      grid_col: 11,
      icon: "/game/community.svg",
    },
    {
      id: 34,
      type: "property",
      name: "Mantle Mall",
      price: 320,
      rent_site_only: 28,
      rent_one_house: 150,
      rent_two_houses: 450,
      rent_three_houses: 1000,
      rent_four_houses: 1200,
      rent_hotel: 1400,
      cost_of_house: 200,
      is_mortgaged: false,
      group_id: 7,
      color: "#008000",
      position: "right",
      grid_row: 5,
      grid_col: 11,
      icon: "/game/mantle.svg",
    },
    {
      id: 35,
      type: "property",
      name: "Base Railroad",
      price: 200,
      rent_site_only: 25,
      rent_one_house: 50,
      rent_two_houses: 100,
      rent_three_houses: 200,
      rent_four_houses: 400,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#000000",
      position: "right",
      grid_row: 6,
      grid_col: 11,
      icon: "/game/base.svg",
    },
    {
      id: 36,
      type: "chance",
      name: "Chance",
      price: 0,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#FFD700",
      position: "right",
      grid_row: 7,
      grid_col: 11,
      icon: "/game/chance2.svg",
    },
    {
      id: 37,
      type: "property",
      name: "Zora Zone",
      price: 350,
      rent_site_only: 35,
      rent_one_house: 175,
      rent_two_houses: 500,
      rent_three_houses: 1100,
      rent_four_houses: 1300,
      rent_hotel: 1500,
      cost_of_house: 200,
      is_mortgaged: false,
      group_id: 8,
      color: "#00008B",
      position: "right",
      grid_row: 8,
      grid_col: 11,
      icon: "/game/zora.svg",
    },
    {
      id: 38,
      type: "income_tax",
      name: "Super Tax",
      price: 100,
      rent_site_only: 0,
      rent_one_house: 0,
      rent_two_houses: 0,
      rent_three_houses: 0,
      rent_four_houses: 0,
      rent_hotel: 0,
      cost_of_house: 0,
      is_mortgaged: false,
      group_id: 0,
      color: "#DC143C",
      position: "right",
      grid_row: 9,
      grid_col: 11,
      icon: "/game/supertax.svg",
    },
    {
      id: 39,
      type: "property",
      name: "Boardwalk",
      price: 400,
      rent_site_only: 50,
      rent_one_house: 200,
      rent_two_houses: 600,
      rent_three_houses: 1400,
      rent_four_houses: 1700,
      rent_hotel: 2000,
      cost_of_house: 200,
      is_mortgaged: false,
      group_id: 8,
      color: "#00008B",
      position: "right",
      grid_row: 10,
      grid_col: 11,
      icon: "/game/boardwalk.svg",
    },
  ]);
};
